### ISSUE TITLE
[Testing Issue]

### ISSUE THREAD

**Issue by peter-evans** [peter-evans/create-or-update-comment#1]
This is an issue used by this action's workflow test cases.

**Comment by peter-evans** [comment]
Test

**Comment by peter-evans** [comment]
Test

**Comment by peter-evans** [comment]
Test

**Comment by afwn90cj93201nixr2e1re** [comment]
@peter-evans i think you should allow multiplie reactions in one step.

'+1, eyes'
and parse dem by comma.

**Comment by afwn90cj93201nixr2e1re** [comment]
@peter-evans i think you should allow multiplie reactions in one step.

'+1, eyes'
and parse them by comma.

**Comment by afwn90cj93201nixr2e1re** [comment]
Test

**Comment by o-az** [comment]
How can I reference commit hash, branch name and commit URL in the comment? This is what I get when I try

```yml
# ...
body: |
  Branch: $GITHUB_REF (${GITHUB_REF#refs/heads/})
  Commit SHA: $GITHUB_SHA
  Commit SHA short: $(git rev-parse --short HEAD)

  # The above as a markdown table
  | Branch | Commit SHA | Commit SHA short |
  | --- | --- | --- |
  | $GITHUB_REF (${GITHUB_REF#refs/heads/}) | $GITHUB_SHA | $(git rev-parse --short HEAD) |
```

Result:

![CleanShot 2023-02-01 at 22 39 09](https://user-images.githubusercontent.com/23618431/216250557-b10c1562-4140-471e-8edb-6f65be493f71.png)
