### ISSUE TITLE
Error: Missing either 'issue-number' or 'comment-id'.

### ISSUE THREAD

**Issue by agorkiy** [peter-evans/create-or-update-comment#104]
Hi
I'm trying to use this step to add comments on both new PR and PR that already exists.
Right now this part github workflow looks like this:
`name: deploy swagger specs

on:
  push:
    paths:
      - 'swagger-/**.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        ...
      - name: Deploy
        run: aws s3 sync .....
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Swagger specs were deployed to https://swagger.example.com/${GITHUB_REF##*/}/example.yaml`

But this workflow fails on Create comment step, with such error:
`Run peter-evans/create-or-update-comment@v1
Error: Missing either 'issue-number' or 'comment-id'.`
I don't know how to troubleshoot this further. I already tried to use github.event.issue.number and github.event.number instead of github.event.pull_request.number but error never changed. Any idea what am I doing wrong? thanks.

**Comment by peter-evans** [comment]
Hi @agorkiy 

The problem is that the context property `github.event.pull_request.number` is not available for events triggered on `push`. You can see in the context path that it expects the event to be `pull_request`. Either you need to run the workflow on `pull_request` events, or you need to find another way to get the pull request number that you need (perhaps by calling the GitHub API).

**Comment by agorkiy** [comment]
@peter-evans hi, thank you, understood.
Now I'm trying to echo branch name in comment body, like this:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Swagger specs were deployed to https://swagger.example.com/${{GITHUB_HEAD_REF}}/example.yaml
But i faced issue that none of github env variables is working here - variable is always blank and url looks like this:
`https://swagger.example.com//example.yaml`
Any idea, how can I fix this?

**Comment by peter-evans** [comment]
Hi @agorkiy 

Try `${{ github.head_ref }}`.

**Comment by agorkiy** [comment]
Ended up using this:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch
And then used ${{ steps.extract_branch.outputs.branch }} as variable.
Thank you for your help.

**Comment by Norfeldt** [comment]
Just gonna share what worked for me:

> ci.pr.yml

```
name: CI

on: 
  pull_request:
    types: [opened]

jobs:
  todo-fixme-comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: get yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn
        run: yarn --frozen-lockfile
      - id: find-pull-request
        uses: jwalton/gh-find-current-pr@v1
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - name: create TODO/FIXME comment body
        id: comment-body
        run: |
          yarn todos --exit-nicely --reporter markdown > TODO.md
          body="$(sed 1,2d TODO.md)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: post TODO/FIXME comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.find-pull-request.outputs.number }}
          body: ${{ steps.comment-body.outputs.body }}   
```

This job pust all the code comments with `// TODO` `// FIXME` as a comment on every PR opening.

then the other jobs that runs on push goes into `ci.push.yml`
