### ISSUE TITLE
Feature request: Delete prior comment and add new

### ISSUE THREAD

**Issue by selfagency** [peter-evans/create-or-update-comment#110]
Thank you so much for making this extremely useful Action. It's been immensely helpful for my workflows. In my use case, I publish unit and E2E test results as comments to my team's PRs. However, I've noticed sometimes on PRs with a lot of commits or lengthy discussions that, due to their age, the comments produced using this Action get buried behind the following separator, and so when they are updated, those updates get lost.

![CleanShot 2022-04-01 at 13 47 10](https://user-images.githubusercontent.com/2541728/161315596-29f3f071-89e1-422d-af68-1db18abbb203.png)

I was hoping you might consider adding a feature that, instead of updating the previous comment, will delete it and add a new comment entirely so that the latest updates always appear on screen.

Thank you!

**Comment by peter-evans** [comment]
Hi @selfagency 

I'm not sure about adding that functionality into this action itself, but what you want to do is very easy to achieve anyway with one extra workflow step to delete the comment.

Change this to suit your use case, but something like this should work.

```yml
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Build output

    - if: steps.fc.outputs.comment-id != ''
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.fc.outputs.comment-id }}
          })

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Build output
          ${{ steps.build.outputs.build-log }}
```
