### ISSUE TITLE
[question] Is body-path relative to root? (Also, some ideas)

### ISSUE THREAD

**Issue by Andre601** [peter-evans/create-or-update-comment#165]
The title pretty much says it.

I think it is, but I wasn't entirely sure either, so I wanted a bit of clarification here.

Also, I would also ask about supported file types.
Like does it need to be a txt file? Or will .md work too? What about other formats?

And finally, will values like context (i.e. `${{ github.event.pull_request.number }}` be properly parsed by GitHub Actions, or would it need to remain in the GitHub workflow file as a body option itself?

If it doesn't parse, maybe offer an option to define placeholders that should be replaced?
Like f.e. in my case:
```yaml
placeholders: |
  commit: ${{ env.HEAD_SHA }}
  logs: ${{ env.LOGS }}
  download: ${{ env.DOWNLOAD }}
```

This could actually even be a good idea to allow much more customizable file templates, by allowing to replace parts within it with values you define.

Like - again - in my personal case would the file look like this...
```markdown
![badge]

{{ text }}

| Name     | Link           |
| -------- | -------------- |
| Commit   | {{ commit }}   |
| Logs     | {{ logs }}     |
| Download | {{ download }} |

[badge]: https://img.shields.io/badge/{{ badge_text }}-0d1117?style=for-the-badge&labelColor={{ badge_color }}&logo={{ badge_logo }}
```
...and when used, I would have a setup like this:
```yaml
- uses: peter-evans/create-or-update-comment@v3
  with:
    issue-number: ${{ github.event.pull_request.number }}
    comment-id: ${{ steps.find-comment.outputs.comment-id }}
    edit-mode: replace
    body-path: ./.github/pr-comment-template.md
    options: |
      text: The build of this pull request was successfull! You can find a download link below.
      commit: ${{ env.COMMIT }}
      logs: ${{ env.LOGS }}
      download: ${{ env.DOWNLOAD }}
      badge_text: Build successful!
      badge_color: 00FF00
      badge_logo: github
```
The only issues I currently would see is how stuff like line-breaks could be implemented and if there should be an option to hide content based stuff like if a placeholder has a value or not... Tho, that all depends on if this is even a good option to add at all...
