### ISSUE TITLE
How to use comment on current PR and populate body from output of previous step

### ISSUE THREAD

**Issue by cameroncooke** [peter-evans/create-or-update-comment#18]
Couple of questions, I want to use this action with a pull request triggered workflow which has a single job. 

What's not clear to me is:

- How can I comment on the PR that triggered the job, the `issue-number` argument requires a hardcoded value but that's not much use in real world, do you have an example on how to do this?

- How can I populate the body of the comment with data from a previous step. Essentially I've created a txt file on the runner which I want to use as the content for the comment. 

Here is an example of my workflow:

```yaml
name: Code Coverage

on: pull_request

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2  
      
    - name: Switch XCode version to 11.4
      run: sudo xcode-select -s /Applications/Xcode_11.4.app
      
    - name: Run code coverage
      run: |
        xcodebuild clean test -project test.xcodeproj -scheme test -destination "platform=iOS Simulator,name=iPhone 11 Pro" -derivedDataPath Build/ -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        xcrun xccov view --report Build/Logs/Test/Run-test-*.xcresult > coverage.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Code Coverage Report
        path: coverage.txt
        
    - name: Add test report comment on PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ????????
        body: |
          ```
          *****content of coverage.txt to go here*****
          ```
        reaction-type: 'rocket'
```

Thanks.

**Comment by peter-evans** [comment]
Hi @cameroncooke 

You can get the issue number from `${{ github.event.pull_request.number }}`. For the content of a file, try setting it in an output variable as shown below. I'm not sure if this works well with multi-line content, but you can try it and see.

```
    - name: Run code coverage
      id: coverage
      run: |
        xcodebuild clean test -project test.xcodeproj -scheme test -destination "platform=iOS Simulator,name=iPhone 11 Pro" -derivedDataPath Build/ -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        xcrun xccov view --report Build/Logs/Test/Run-test-*.xcresult > coverage.txt
        echo ::set-output name=result::$(cat coverage.txt)

    - name: Add test report comment on PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ```
          ${{ steps.coverage.outputs.result }}
          ```
        reaction-type: 'rocket'
```
