### ISSUE TITLE
NaN when using github.event.number

### ISSUE THREAD

**Issue by nickelghost** [peter-evans/create-or-update-comment#22]
Hello, I'm using this action like that:
```yml
     - name: Publish URLs
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
```
and it returns the following error:
```
##[error]Invalid value for parameter 'issue_number': "github.event.number" is NaN
```
I guess that it's because there isn't a string to int conversion in the action. However, actions don't provide data type conversion, so it's impossible for me to use this action.
