### ISSUE TITLE
How to create comment that from a txt file?

### ISSUE THREAD

**Issue by seepine** [peter-evans/create-or-update-comment#237]
like output.txt, it has multiple lines of text
```
actions ci auto build start...
install success
compile success
actions ci finish
```
I try, but failure
```
      - name: Generate QrCode
        id: log
        run: |
          echo "LOGS=$(cat output.txt)" >> $GITHUB_OUTPUT

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build success
            ${{ steps.log.outputs.LOGS }}
```

**Comment by peter-evans** [comment]
Hi @seepine 

You can use the `body-path` input to specify the path to a comment body.

```yml
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: output.txt
```
