### ISSUE TITLE
Add multiple reactions in a single execution of the action

### ISSUE THREAD

**Issue by peter-evans** [peter-evans/create-or-update-comment#26]
Thank you @afwn90cj93201nixr2e1re for this feature suggestion.

Planning to add a new `reactions` input allowing multiple comma separated reactions to be added to a comment.
```
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: 557858210
          reactions: heart, eyes, +1
```
