### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by fingolfin** [peter-evans/create-or-update-comment#323]
We are using this wonderful GH action to create PR comment -- but also very often to *update* PR comments (see <https://github.com/gap-system/PackageDistro/blob/main/.github/workflows/pull-request.yml> for our full YAML file):
```
      - name: "Create or update comment"
        uses: peter-evans/create-or-update-comment@v4   
        with:
          token: ${{ steps.generate-token.outputs.token }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
```

Today this workflow suddenly had failures I never saw before (although I should say we had been using v2 until 19 February 2024), when it tried to update an existing PR (actually the update in this case would be identical to the existing PR, which so far worked perfectly -- it just did nothing).

There error ([see here for full log](https://github.com/gap-system/PackageDistro/actions/runs/8263626286/job/22605528683#step:6:522)):
```
Create or update the pull request
  Attempting creation of pull request
  A pull request already exists for gap-system:automatic/cap_project
  Fetching existing pull request
  Attempting update of pull request
  Error: Cannot read properties of undefined (reading 'number')
```
