### ISSUE TITLE
Error: Missing comment 'body' or 'body-path'.

### ISSUE THREAD

**Issue by dmzeus** [peter-evans/create-or-update-comment#331]
Hello!

I got this error when I wanted to add reaction to existing comment in PR:
```yaml
- name: Put starting reaction to the comment
  uses: peter-evans/create-or-update-comment@v4
  with:
    comment-id: ${{ env.NODE_ID }}
    issue-number: ${{ env.PR_NUMBER }}
    reactions: eyes
```

**Comment by dmzeus** [comment]
Output from GHA:
```
Run peter-evans/create-or-update-comment@v4
  with:
    comment-id: ***
    issue-number: ***
    reactions: eyes
    token: ***
    repository: ***
    edit-mode: append
    append-separator: newline
    reactions-edit-mode: append
  env:
    PR_NUMBER: ***
    NODE_ID: ***
    REPO: ***
Error: Missing comment 'body' or 'body-path'.
```

**Comment by peter-evans** [comment]
Hi @dmzeus 

It's probably because the `commend-id` value is empty or null. Check that there is a value being supplied by `env.NODE_ID`.

See the logic here:
https://github.com/peter-evans/create-or-update-comment/blob/8da4c50e7142257262c9df90da4e74a59068c038/src/main.ts#L59-L69

**Comment by dmzeus** [comment]
Hi! @peter-evans 

Tried again with these values:
```
Run peter-evans/create-or-update-comment@v4
  with:
    comment-id: IC_kw*** # comment-id placed here from ${{ github.event.comment.node_id }} instead env
    reactions: eyes
    body: [bot] Task started
    edit-mode: append
    token: ***
    repository: ***
    append-separator: newline
    reactions-edit-mode: append
```
And got an error:
`Error: Missing either 'issue-number' or 'comment-id'.`
