### ISSUE TITLE
Create works but update doesn't?

### ISSUE THREAD

**Issue by PureKrome** [peter-evans/create-or-update-comment#364]
Hi there 👋🏻 

I'm testing this GH Action out and I can't seem to Update an existing comment which this Action created. It keeps creating the a new comment each time.

The content of the comment is from a markdown file -> code coverage results. These are usually dynamic with each PR-commit that is pushed up.

I'm _guessing_ this might be because it cannot find the hidden html comment? my markdown content overrides it?

# Suggestion: New Action inputs

|Name|Description|Info|
|----|-----------|----|
|`secret-key`|A secret piece of HTML text that is prepended to any content. This is an HTML Comment|`secret-html-hidden-value` (which ends up becoming `<!-- secret-html-hidden-value -->`|

example:

```
- name: Create or Update PR Comment
    uses: peter-evans/create-or-update-comment@v4
    with:
        issue-number: ${{ github.event.pull_request.number }}
        secret-key: i-am-your-father
        body-file: code-coverage-results.md
        edit-mode: replace
```

I don't care what that value is. it's just something which should NOT be part of my markdown file or the body text/content i manually provide.

This means we wouldn't have use your `find-comment` action.

Maybe the default is `empty string` so nothing is pre-pended? and if the value is provided then it is pre-pended and wrapped in the `<!-- -->` html comment element.

**Comment by peter-evans** [comment]
Hi @PureKrome 

> I'm guessing this might be because it cannot find the hidden html comment? my markdown content overrides it?

I think find-comment should be able to find that. It's just searching the text of the comment body. The markdown rendering should have nothing to do with it. If you show me your workflow and perhaps a log of the run we might be able to work out why it doesn't work for you.

**Comment by PureKrome** [comment]
👋🏻 Hi @peter-evans - thanks heaps for prompt reply. Legend!

Here's my existing workflow:

```
- name: Create or Update PR Comment
    uses: peter-evans/create-or-update-comment@v4
    with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: code-coverage-results.md
        edit-mode: replace
```
So there's nothing crazy here. 

I'm not using `find-comment`. What I was _hoping_ was that I didn't need to use that action but _this action_ could do the replace _automatically_ and that was why I was thinking "how would it know to replace" and this is because it is looking for that secret html which this action can _auto_ add into the comment.
