### ISSUE TITLE
Cannot add reaction to the main comment of a review

### ISSUE THREAD

**Issue by lugi0** [peter-evans/create-or-update-comment#392]
Hi,

I'm trying to leave a reaction on the main comment that is created when a user leaves a review from the diff view (so not the inline comments the review might contain).
This is the code I'm using

```
- name: Acknowledge the review with thumbs up reaction
        if: ${{ github.event.review }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.review.id }}
          reactions: '+1'
```

I can see from the actions logs that this step is running and seeing both the review and comment

```
Run peter-evans/create-or-update-comment@v4
  with:
    comment-id: <my-comment-id>
    reactions: +1
    token: ***
    repository: <my-repo>
    edit-mode: append
    append-separator: newline
    reactions-edit-mode: append
Warning: Adding reaction '+1' to comment id '<my-comment-id>' failed.
```

And you can see it fails to add the reaction. I am assuming that review.id is the id of the comment, since review.body is the body of the comment. Is that a wrong assumption?
