### ISSUE TITLE
Accept a file as the comment body

### ISSUE THREAD

**Issue by ghostsquad** [peter-evans/create-or-update-comment#51]
This is a request to accept a file as the comment body, such that comments can be more easily dynamically generated.

**Comment by peter-evans** [comment]
Hi @ghostsquad 

Did you know you can just read the file into a variable and pass it to the action like this:
```
      - id: get-issue-body
        run: echo ::set-output name=body::$(cat my-issue-body.txt)

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: ${{ steps.get-issue-body.outputs.body }}
```
