### ISSUE TITLE
Add list of users or groups for whom no comment is created

### ISSUE THREAD

**Issue by abenettt** [peter-evans/create-or-update-comment#53]
When certain people open an issue on a repository, like for example the owner themselves, there might be no need to create a comment on the issue. With a pass list users and groups could be specified for whom the action does not create comments.

**Comment by peter-evans** [comment]
Hi @abenettt 

This action is designed to be generic and have a simple interface in order to make it usable in many different workflows. The kind of logic you are interested in doing I think would be best suited to living in the workflow itself or some other action.

Just as an example, you can use the [author_association](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) property to decide whether to create a comment or not.

```
      - if: github.event.issue.author_association != 'OWNER' && github.event.issue.author_association != 'COLLABORATOR'
        name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Thanks for making an issue!
```

Will something similar to this example cover your use case?
