### ISSUE TITLE
Error - Missing either 'issue-number' or 'comment-id' - How to not run the step conditionally?

### ISSUE THREAD

**Issue by Vadorequest** [peter-evans/create-or-update-comment#64]
I'm trying to handle an edge case where my workflow fails because there is no existing branch to write the comment to.

My goal is to not run the `Comment PR (Deployment failure)` step when the `${{ steps.pr_id_finder.outputs.number }}` is not defined, but I don't really understand how to do that.

```yml

      # We need to find the PR id. Will be used later to comment on that PR.
      - name: Finding Pull Request ID
        uses: jwalton/gh-find-current-pr@v1
        id: pr_id_finder
        if: always() # It forces the job to be always executed, even if a previous job fail.
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # On deployment failure, add a comment to the PR, if there is an open PR for the current branch
      - name: Comment PR (Deployment failure)
        uses: peter-evans/create-or-update-comment@v1
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.pr_id_finder.outputs.number }}
          body: |
            :x:&nbsp; Deployment **FAILED**
            Commit ${{ github.sha }} failed to deploy to [${{ env.ZEIT_DEPLOYMENT_URL }}](${{ env.ZEIT_DEPLOYMENT_URL }})
            [click to see logs](https://github.com/UnlyEd/TFP-v4/pull/${{ steps.pr_id_finder.outputs.number }}/checks)

```

I tried to do 
```yml
      - name: Comment PR (Deployment failure)
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.pr_id_finder.outputs.number }} && failure()
		...
```

But it didn't work out. Would you know how to achieve it?

**Comment by Demmonius** [comment]
HI @Vadorequest,
Did you try:
```
      - name: Comment PR (Deployment failure)
        uses: peter-evans/create-or-update-comment@v1
        if: steps.pr_id_finder.outputs.number && failure()

```
You don't need to specify any expression syntax
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif

**Comment by Vadorequest** [comment]
Thank you, I can confirm `steps.pr_id_finder.outputs.number && failure()` works perfectly.

```yml
      # On deployment failure, add a comment to the PR, if there is an open PR for the current branch
      - name: Comment PR (Deployment failure)
        uses: peter-evans/create-or-update-comment@v1
        if: steps.pr_id_finder.outputs.number && failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.pr_id_finder.outputs.number }}
          body: |
            :x:&nbsp; Deployment **FAILED**
            Commit ${{ github.sha }} failed to deploy to [${{ env.ZEIT_DEPLOYMENT_URL }}](${{ env.ZEIT_DEPLOYMENT_URL }})
            [click to see logs](https://github.com/UnlyEd/TFP-v4/pull/${{ steps.pr_id_finder.outputs.number }}/checks)
```
