### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by staabm** [peter-evans/create-or-update-comment#76]
I try to post a string to create a comment, but getting a `Resource not accessible by integration` error

see action logs https://github.com/parsica-php/parsica/pull/37/checks?check_run_id=2113059121

![grafik](https://user-images.githubusercontent.com/120441/111164339-4a21fb00-859e-11eb-87bb-e77a4b2bfd2b.png)

maybe one of the ansi special chars is a problem?

**Comment by staabm** [comment]
the workflow in question is pretty simple / the comment part was more or less copied from the actions readme:

```
name: Benchmark

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: create perf comparison
      id: perf-compare
      run: |
        # create baseline
        git checkout cc0808fd2ecd30a563bbe20e5d4e989d7071aa03
        composer install --prefer-dist --no-progress --no-suggest
        composer benchmark-baseline
        
        # cleanup
        rm composer.lock
        
        # compare against current commit
        git checkout ${{ github.event.pull_request.head.sha }}
        composer install --prefer-dist --no-progress --no-suggest
        comparison=$(composer benchmark-compare-baseline)

        # prepare multi line message
        comparison="${comparison//'%'/'%25'}"
        comparison="${comparison//$'\n'/'%0A'}"
        comparison="${comparison//$'\r'/'%0D'}"
        
        echo "::set-output name=comparison::$comparison"

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: running benchmarks...

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
            ```
            ${{ steps.perf-compare.outputs.comparison }}
            ```

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
            ```
            ${{ steps.perf-compare.outputs.comparison }}
            ```
```

https://github.com/staabm/parsica/blob/c1ed7e515430bdb028eb4eeffafce2c731ac52ca/.github/workflows/benchmark.yml

**Comment by peter-evans** [comment]
This is because the `pull_request` event has been triggered by a fork. There is a [note in the readme](https://github.com/peter-evans/create-or-update-comment#action-inputs) about this scenario.

> Note: In *public* repositories this action does not work in `pull_request` workflows when triggered by forks.
This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event to comment on pull requests.

**Comment by staabm** [comment]
Thanks for noticing. 

UX wise it would be great to reflect the underlying problem in the error message

**Comment by peter-evans** [comment]
Yes, it's not very clear from GitHub's error message what the problem is. I'll see if I can catch this particular error and display something more meaningful.

**Comment by staabm** [comment]
Thanks!

**Comment by yasirroni** [comment]
> This is because the `pull_request` event has been triggered by a fork. There is a [note in the readme](https://github.com/peter-evans/create-or-update-comment#action-inputs) about this scenario.
> 
> > Note: In _public_ repositories this action does not work in `pull_request` workflows when triggered by forks.
> > This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event to comment on pull requests.

I'm still not understanding this.

Here is my case:

Someone have a repo.

I make a fork.

I add this piece of code in CI `.yml`:

```
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.template.outputs.result }}
```

A make a PR. 

How and where to set `[pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target)` to make the github action able to comment on PR made by public fork without asking the developer to configured [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks)?

**Comment by yasirroni** [comment]
Based on [this asnwer](https://github.community/t/pull-request-target-not-triggering-workflow/163924/5), [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) will work after `pull_request_target` event exist in the targeted branch. Thus (example for master branch), first, use:

```
on:
  on:
  pull_request_target:
    branches: [ master ]:
    branches: [ master ]
```

Then merge first to master.

If any fork push to the master branch, the `pull_request_target` will be triggered.
