### ISSUE TITLE
Create comment from template file

### ISSUE THREAD

**Issue by Ameausoone** [peter-evans/create-or-update-comment#79]
It could be interesting to create comment from a template file.

An example : https://github.com/JasonEtco/create-an-issue#custom-templates. 

## Example
``` 
steps:
  - uses: actions/checkout@v2
  - uses: peter-evans/create-or-update-comment@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      filename: .github/some-comment-template.md
```

(Thx for your work).

**Comment by peter-evans** [comment]
Hi @Ameausoone 

Rather than put this functionality in the action I would like to recommend using the [render-template](https://github.com/chuhlomin/render-template) action to achieve this.

Here is an example template file, `comment-template.md`
```
This is a test comment template

Render template variables such as {{ .foo }} and {{ .bar }}.
```

This is an example workflow to render it and create a comment.
```yml
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/comment-template.md
          vars: |
            foo: this
            bar: that

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: ${{ steps.template.outputs.result }}
```
