### ISSUE TITLE
Combine create and update in a single configuration?

### ISSUE THREAD

**Issue by robdodson** [peter-evans/create-or-update-comment#9]
Hello 👋

I was wondering if you would consider a PR which slightly changes the behavior of the Action to allow someone to create or update in a single configuration? My use case is I wanted to have a comment at the top of my PR that shows lint status. If it's the first the linter has run, it will create this comment. On subsequent runs, it will update this comment using `replace`.

Currently the Action will always create a new comment if an issue number is passed. Here's the relevant snippet of code:

```js
if (inputs.issueNumber) {
  ...
} else if (inputs.commentId) {
  ...
}
```

However, if you swap the order of the condition, then you can have it first check for a comment-id to update, and if one isn't passed it will check for an issue number to create a new comment:

```js
if (inputs.commentId) {
  ...
} else if (inputs.issueNumber) {
  ...
}
```

That enables a workflow like this:

```yml
# This finds the first comment id from the GitHub Actions bot.
# If it hasn't commented on the issue or PR yet then it returns an empty string.
- name: Find comment
  id: find_comment
  uses: ./.github/actions/find-comment
  with:
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Create or update comment
  # I forked a version of this repo to implement the above mentioned conditional
  uses: robdodson/create-or-update-comment@master
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    issue-number: ${{ github.event.number }}
    # If the comment-id is blank, this will create a new comment.
    # Otherwise, it will update the comment.
    comment-id: ${{ steps.find_comment.outputs.comment-id }}
    body: |
      Create or update this comment.
    edit-mode: replace
  if: success()
```

I realize you could also achieve this by writing two steps and using `if` to check if it should create or update the comment, but that felt a bit noisy to me. If you'd be open to this change then I could send over a PR. I also understand if you'd prefer to keep the Action as is because it matches your use case :)
