### ISSUE TITLE
Creating/updating comment on push event

### ISSUE THREAD

**Issue by htd-tstepien** [peter-evans/create-or-update-comment#90]
So I'm trying to update PR with comment with results written in \`md\` on each push from generated file, but event "push" doesn't have property "number" so I can't search/update PR for comment. How to do that, or bypass?

This is what I have so far.

```
name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        
      # Create md report from generated reports
      - name: Merge generated reports into one
        run: yarn run merge:reports
        
      - name: Create md report
        run: yarn run create:markdown:report
        
      # Read created md
      - name: Read md content
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "merged.md"
          
      # Create or update comment in PR
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.read_file.outputs.contents }}
          edit-mode: replace
```
