### ISSUE TITLE
Comment body too big causing an error - any suggestion ?

### ISSUE THREAD

**Issue by DanyC97** [peter-evans/create-or-update-comment#96]
hi @peter-evans ,

first of all kudos for this action, it works so nicely !

Secondly, as i was using your action to add a big comment (TF plan output) i've bumped into an error like `Error: Argument list too long`

It it something which can be done to increase the size ?

**Comment by DanyC97** [comment]
i should have mentioned that the step looks like

```
    - name: Create PR comment
      uses: peter-evans/create-or-update-comment@v1
      if: |
        contains(github.event.client_payload.slash_command.args.all, 'env=') &&
        contains(github.event.client_payload.slash_command.args.unnamed.arg1, 'plan')
      with:
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body: ${{ env.TFPLAN_RESPONSE }}
```

**Comment by tarfeef101** [comment]
@DanyC97 I have previously run into and solved this with previous work, but since that was created for private companies, I sadly cannot just hand you the code. But I can say I was inspired by https://github.com/runatlantis/atlantis, who have also solved this problem for the same reason. I cannot recall where in their codebase they solved this issue, but I'm sure you can sleuth it pretty quickly. It'll require modifying wherever you're calling the comment API to do so iteratively, but at least you can get some of the information (including max comment size) from someone who's already run into it.

**Comment by peter-evans** [comment]
Hi @DanyC97 

Based on [this PR](https://github.com/robburger/terraform-pr-commenter/issues/6), it looks like this error is not caused by the GitHub API but from the Actions runner when it tries to handle passing arguments between steps. There is some further explanation in [this linked PR](https://github.com/actions/virtual-environments/issues/3257).

Are you using self-hosted runners?
If you are using GitHub's runners, they now seem to have a 16MB limit for arguments. Is it larger than that? If so, I don't think there is any other option other than to truncate the message or handle it in chunks somehow. I don't think this action can do anything to help with that.

**Comment by tarfeef101** [comment]
If you want to pass an entire plan between steps, consider this fact:
```
Each step in a job executes on the same runner, allowing the actions in that job to share data with each other.
```

You can just use files for this. 

However, I suggest you just do a little scripting and call a script in a single step rather than use file I/O and multiple steps to do this. Since you'll need to script handling giant comments anyway, you're gonna need complex steps no matter what.

**Comment by DanyC97** [comment]
@tarfeef101 many thanks for your input, glad i wasn't the only one who bumped into it. I'll surely look at atlantis.

fyi how i build the PR comment, i had to go with an env otherwise the plan output format was getting screwed 

```
 - name: Create PR comment body
      id: comment_body
      if: |
        contains(github.event.client_payload.slash_command.args.all, 'env=') &&
        contains(github.event.client_payload.slash_command.args.unnamed.arg1, 'plan')
      env:
        TF_ENV: ${{ github.event.client_payload.slash_command.args.named.env }}
        TF_PLAN: "```${{ steps.plan.outputs.tfplan }}"
      run: |
        echo 'TFPLAN_RESPONSE<<EOF' >> $GITHUB_ENV
        echo "<!-- magic:comment -->" >> $GITHUB_ENV
        echo "_Terraform generated plan for - $TF_ENV - tfvars file_">> $GITHUB_ENV
        echo "Update Date: $(date +'%Y-%m-%d %H:%M:%S %z')" >> $GITHUB_ENV
        echo "Compare: https://github.com/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        echo "$TF_PLAN" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

```

**Comment by DanyC97** [comment]
> Hi @DanyC97
> 
> Based on [this PR](https://github.com/robburger/terraform-pr-commenter/issues/6), it looks like this error is not caused by the GitHub API but from the Actions runner when it tries to handle passing arguments between steps. There is some further explanation in [this linked PR](https://github.com/actions/virtual-environments/issues/3257).
> 
> Are you using self-hosted runners? If you are using self-hosted, try increasing the stack size in the same way as the above linked PR.

indeed i'm using self-hosted runners (EC2 on which GH runner docker image runs). I'll look at increasing the stack size as suggested , many thanks for swift response.

**Comment by DanyC97** [comment]
okay folks i've given up ..

I went down the rabbit hole and tried to get docker daemon to recognise my newer `--ulimit stack` value and after many hours i've managed to get a different value however 16/32MB didn't work.

Then thinking it may be due to my self-hosted runners , i went ahead and used a stock public runner, where i've run the below

```
  push-pr-comment:
    runs-on: ubuntu-latest
    needs: run-terraform

    steps:
    - name: Get ulimit stack space allocation
      run: ulimit -s 65536

    - name: Create PR comment body
      id: comment_body
      if: |
        contains(github.event.client_payload.slash_command.args.all, 'env=') &&
        contains(github.event.client_payload.slash_command.args.unnamed.arg1, 'plan')
      env:
        TF_ENV: ${{ github.event.client_payload.slash_command.args.named.env }}
        TF_PLAN: "```${{ needs.run-terraform.outputs.TF_PLAN_D }}"
      run: |
        echo 'TFPLAN_RESPONSE<<EOF' >> $GITHUB_ENV
        echo "<!-- magic:comment -->" >> $GITHUB_ENV
        echo "_Terraform generated plan for - $TF_ENV - tfvars file_">> $GITHUB_ENV
        echo "Update Date: $(date +'%Y-%m-%d %H:%M:%S %z')" >> $GITHUB_ENV
        echo "Compare: https://github.com/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        echo "$TF_PLAN" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Find magic comment
      uses: peter-evans/find-comment@v1
      id: magic_comment
      if: |
        contains(github.event.client_payload.slash_command.args.all, 'env=') &&
        contains(github.event.client_payload.slash_command.args.unnamed.arg1, 'plan')
      with:
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body-includes: "<!-- magic:comment -->"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete PR comment
      uses: actions/github-script@v4
      if: steps.magic_comment.outputs.comment-id != 0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.magic_comment.outputs.comment-id }},
          })

    - name: Create PR comment
      uses: peter-evans/create-or-update-comment@v1
      if: |
        contains(github.event.client_payload.slash_command.args.all, 'env=') &&
        contains(github.event.client_payload.slash_command.args.unnamed.arg1, 'plan')
      with:
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body: ${{ env.TFPLAN_RESPONSE }}

```

Again using 32 and then 64 made no difference.
