### ISSUE TITLE
Action running without progress

### ISSUE THREAD

**Issue by timmeinerzhagen** [peter-evans/create-or-update-comment#99]
Yesterday, the action started as usual but never finished. After about an hour I canceled it because I was very confused. See the image below.

![image](https://user-images.githubusercontent.com/34220101/147588834-193c62cb-dda9-469e-8d9d-648bf599bd43.png)

After running the exact same workflow again a little later, it worked without any issue. This could be related to the GitHub Actions outage yesterday (see [GitHub status entry](https://www.githubstatus.com/incidents/gh0vvxtlj5v7)), but the action actually ran a few hourse before the reported starting date for the incident. Not sure what else could have caused this.

Here is the workflow I'm using:

```
on:
  issues:
    types:
      - assigned

jobs:
  ## Before deploy let user now it is running ##
  issue-comment-confirm:
    name: Comment Start
    if: contains(github.event.issue.assignee.login, 'timmeinerzhagen')

    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1.4.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            <message>
```
